export const RAW_SHORTCUTS = `
# Shortcut_List_Part1 (A-Chi)
klaxon = Air Horn
luftskip = Airship, Blimp
budik/wekker = Alarm Clock
obcy = Alien
ambulan = Ambulance
kotva = Anchor
ange = Angel
arg = Angry
dyr = Animal
stad = Anvil
apa = Ape, Monkey
apocalyp = Apocalypse
mar = Apple, Mars
eplepai = Apple Pie
pom = Apple Tree
aquario = Aquarium, Fish Bowl
arkad = Arcade
arcas = Archer
reka = Arm, Hand
Sip = Arrow
atmosfar = Atmosphere
host = Autumn
avocat = Avocado
palkinto = Award, Trophy
bambino = Baby, Kid
batoh = Backpack
spek = Bacon
borsa = Bag, Handbag, Purse
bageta = Baguette
cozer = Baking
bald = Bald Head
globo = Balloon, Globe
bambu = Bamboo
banan = Banana
band = Band, Ribbon, Tape, Tyre
side = Bandage
bank = Bank, Bench, Couch
banner = Banner, Flags
bbq = Barbeque
schuur = Barn, Shack, Shed
sud = Barrel
este = Barrier
basebol = Baseball
honkbalveld = Baseball Field
cos = Basket, Cart
baschet = Basketball
basketplan = Basketball Court
banheira = Bath, Hot Tub, Tub
bad = Bath, Bathroom, Boat
pile = Battery
slagskib = Battleship
plaz = Beach
badboll = Beach Ball
strandfest = Beach Party
puf = Bean Bag
cepice = Beanie, Hat, Cap
bar = Bear, Berry, Berries, Bar, Saloon
bart = Beard, Moustache
bobr = Beaver
ape = Bee, Honeybee
Μέλισσα = Bee, Wasp, Bumblebee
humla = Bumblebee
biff = Beef, Steak
ul = Beehive
alveare = Beehive, Honeycomb
kafer = Beetle, Bug
pa = Belt, Spade, Shovel
bel = Bell, Bubble
velo = Bike, Bicycle
kolo = Bike, Hole, Circle, Wheel
poubelle = Bin, Trash Can, Garbage Bin
kikare = Binoculars
ninho = Bird Nest
gaiola = Birdcage
bursdag = Birthday
kek = Biscuit, Cookie, Muffin
sorthul = Black Hole
tavle = Blackboard, Whiteboard
koc = Blanket
lohe = Blaze
mixer = Blender
nevao = Blizzard
bloki = Blocks
bordspel = Board Game
lod = Boat, Ship
bobsled = Bobsledding
bom = Bomb
o = Bone, Island
carte = Book, Map
libreria = Book Shelf, Bookstore
marcaj = Bookmark
bumeran = Boomerang
sko = Boots, Shoes
ram = Border, Frame
fle = Bottle
Hupfburg = Bouncy Castle
fluga = Bow Tie
luk a sip = Bow And Arrow
kom = Bowl
bolo = Bowling
bowlingbal = Bowling Ball
keila = Bowling Pin
chokladask = Box Of Chocolate
box = Boxing, Box
boxring = Boxing Ring
naramek = Bracelet
mozg = Brain
tak = Branch, Twig, Ceiling, Roof
brood = Bread, Loaf Of Bread
frokost = Breakfast, Lunch
bro = Bridge
brokul = Brocolli
roto = Broken
kost = Broom, Broomstick, Bone
pedzel = Brush, Paintbrush
hink = Bucket
bufe = Buffet
budova = Building
autodrom = Bumper Cars
byk = Bull
raivoso = Bulldozer
litera = Bunk Bed
lapin = Bunny, Rabbit
hamburger = Hamburger, Burger
autobuz = School Bus, Bus
ker = Bush
voi = Butter
motyl = Butterfly
knap = Button
taxi = Taxi, Cab
sla = Cabbage, Lettuce
cabana = Cabin, Hut, Shack
Хижина = Log Cabin, Hut, Shack, Cabin
armario = Cupboard, Cabinet, Wardrobe, Closet
cable = Cable, Wire
cactu = Cactus
bur = Cage
torta = Cake, Pie, Torch
laskin = Calculator
agenda = Calendar
tarnung = Camouflage
falo = Campfire
kemp = Campground
lata = Can, Tin Can
vela = Candle
slik = Candy
acadea = Candy Cane
bengala = Cane, Sparkler, Flare
tun = Cannon, Tuna
ghiulea = Cannonball
kajak = Canoe, Kayak, Rowboat
cape = Cape, Cloak
zingend = Carolling
carta = Card, Paper, Letter
kortspil = Card Games
karton = Cardboard Box
caribe = Caribbean
tesar = Carpenter
tapi = Carpet, Rug
vogn = Carriage, Wagon, Cart, Trolley
mrkev = Carrot
dinero = Cash, Money
kassa = Cashier
burg = Castle
ritsa = Catapult
rup = Caterpillar
pata = Cauldron
takflakt = Ceiling Fan
fira = Celebrate
cella = Cell, Prison Cell
celular = Phone, Cellphone, Smartphone
korn = Cereal
lant = Chain
drujba = Chainsaw
stol = Chair, Table
giz = Chalk
damier = Checkerboard
ost = Cheese
ostburgare = Cheeseburger
sernik = Cheesecake
kok = Chef, Cook, Kitchen
cereza = Cherry, Cherries
sah = Chess
kist = Chest
kastan = Chestnut
peto = Chestplate
kana = Chicken, Hen
kurecizokej = Chicken Jockey
kipnugget = Chicken Nugget
piment = Chilli, Chili Pepper

# Shortcut_List_Part2 (Chi-For)

camino = Chimney, Fireplace, Pathway
cin = China
suklaa = Chocolate
chokladkaka = Chocolate Bar
suklaakakku = Chocolate Cake
cookie = Chocolate Chip Cookie, Cookie
chocolaterie = Chocolate Factory
suklaamaito = Chocolate Milk
hashi = Chopsticks
jul = Christmas, Holiday
julkort = Christmas Card
julgran = Christmas Tree
julely = Christmas Lights, Holiday Lights
kerk = Church
kino = Cinema, Movie Theatre
circ = Circus
muschel = Clam, Shell
klo = Claw
jil = Clay
utes = Cliff
escalar = Climbing, Rock Climbing
ur = Clock, Watch, Bear
nori = Clouds
clownvi = Clown Fish
jas = Coat, Jacket
kol = Coal
vesak = Coat Hanger
ragnatela = Cobweb, Web, Spider Web
svab = Cockroach
coco = Coconut
kokon = Cocoon
cafe = Coffee
kaffekop = Coffee Cup
kavovar = Coffee Machine
sarg = Coffin
kredka = Colored Pencil, Crayon
kam = Comb, Hair Brush, Hairbrush
kompa = Compass
dator = Computer
show = Concert
bau = Construction
controller = Controller, Games Controller
forderband = Conveyor Belt
kakmonster = Cookie Monster
cocina = Cooking, Kitchen
hotdog = Hot Dog, Corn Dog
roh = Corner, Horn
hattara = Cotton Candy
棉花糖 = Cotton Candy, Marshmallow
sofa = Couch, Sofa
ko = Cow
koebel = Cowbell
etabli = Crafting Table
gru = Crane
krat = Crate
card = Credit Card, Card
grilo = Cricket
criminal = Criminal, Thug
krokodyl = Crocodile
kuse = Crossbow
fortau = Crosswalk, Sidewalk
lom = Crowbar
cruise = Cruise Ship, Cruise
kostka = Cube, Dice
kop = Mug, Cup
kopvand = Cup Of Water
tenda = Curtain
kyklop = Cyclops
far = Dad, Sheep
narci = Daffodil
dagger = Dagger, Knife
parkiet = Dancefloor
zi = Day
zubar = Dentist
desert = Desert, Dessert
mesa = Desk, Table
cena = Dinner
erdhau = Dirt House
cd = Disc
prato = Dish, Plate
zmywarka = Dishwasher
automat = Dispenser, Vending Machine
buceo = Diving, Scuba Diving
vippe = Diving Board, Seesaw
trefbal = Dodgeball
pie = Dog, Foot, Feet, Pie
obojek = Dog Collar
cachorro = Dog, Puppy
pop = Doll, Puppet
dolar = Dollar
dockhu = Dollhouse
delfin = Dolphin
ane = Donkey
lochy = Dungeon
dona = Donut
tur = Door
pomello = Door Knob
drak = Dragon
drakagg = Dragon Egg
vazka = Dragonfly
desen = Drawing
saty = Dress
bore = Drill
drankje = Drink, Potion
alee = Driveway
garagem = Driveway, Garage
baqueta = Drum Sticks
and = Duck, Genie
trpaslik = Dwarf, Gnome
peso = Dumbbell, Weights
tyrma = Dungeon
tnt = TNT, Dynamite
vultur = Eagle, Vulture
oorbel = Earring
erde = Earth, Soil
pask = Easter
paashaa = Easter Bunny
paasei = Easter Egg
al = Eel
lilek = Eggplant
cot = Elbow
slon = Elephant
hei = Elevator
lumous = Enchant
enderdraak = Ender Dragon
anglie = England
plic = Envelope
miljo = Environment
gum = Eraser, Gum
roltrap = Escalator
kokeilu = Experiment
exploze = Explosion
pala = Eye Patch
ceja = Eyebrow
usine = Factory, Plant
fata = Fairy, Face, Girl
perhe = Family
hek = Fence, Witch
noria = Ferris Wheel
handspinner = Fidget Spinner
pole = Field
palec = Finger, Thumb
meta = Finish Line
ild = Fire
brandbil = Fire Engine
gasnica = Fire Extinguisher
vuurbal = Fireball
hasic = Firefighter
vuurwerk = Fireworks
ensiapu = First Aid
pez = Fish
pescar = Fishing, Fisherman
angel = Fishing Rod, Angel
vlam = Flame
flaming = Flamingo
torcia = Flashlight, Torch
phone = Flip Phone
palme = Flipper
svavande o = Floating Island
sol = Floor, Sun
maceta = Flowerpot
fleur = Flowers
flet = Flute
map = Folder, Map
mad = Food, Cook
fotboll = Football, Soccer
fodboldbane = Football Field
stopa = Footprint
testa = Forehead, Head
bo = Forest
bosbrand = Forest Fire
fork = Fork, Pitchfork
lyckokaka = Fortune Cookie
fonte = Fountain, Smelting
fyrklover = Four Leaf Clover
chips = French Fries, Potato Chips
fortres = Fortress

# Shortcut_List_Part3 (Fri-Met)

fridge = Fridge, Refrigerator
frisbi = Frisbee
sapo = Frog, Toad
owoc = Fruit
obstkorb = Fruit Basket
panev = Frying Pan, Pan
ovn = Furnace, Oven
mobel = Furniture
galax = Galaxy
jogo = Game, Video Game, Video Games
pelituoli = Gaming Chair
lixo = Garbage, Litter, Rubbish, Bin
sopbil = Garbage Truck
have = Garden
pandeajo = Garlic Bread
tore = Gates
lampa = Genie Lamp, Lamp
das = Ghast
duch = Ghost
obr = Giant
gave = Gift, Present (not gifts)
kagemand = Gingerbread Man
lebkuchenhaus = Gingerbread House
giraf = Giraffe
gla = Glass, Jar
glasmelk = Glass Of Milk
bril = Glasses, Goggles
luva = Gloves, Mittens
lim = Glue
gol = Goal
portar = Goalkeeper
ged = Goat
kobold = Goblin, Leprechaun
or = Gold
gulleple = Golden Apple
goudvi = Goldfish
golfkar = Golf Cart
golfbane = Golf Course
gas = Goose
goryl = Gorilla
uva = Grapes
graf = Graph
sarance = Grasshopper
grav = Grave, Mine
gru = Gravel
kerkhof = Graveyard
vert = Green
sera = Greenhouse
vogter = Guardian
gitar = Guitar
chicle = Gum, Gumball
sala = Gym, Room, Living Room
har = Hair
bandana = Hair Band, Headband
uce = Haircut
gang = Hallway
hamer = Hammer
hamac = Hammock
krecek = Hamster
pouta = Handcuffs
planare = Hanggliding
kattely = Handshake
stojka = Handstand
glad = Happy
cai = Harbor, Pier
spukhau = Haunted House
ho = Hay
kopf = Head, Skull
ecouteur = Headphones, Headset
hart = Heart
arbusto = Hedge, Bush
jez = Hedgehog
elicopter = Helicopter
helm = Helmet
kuurupiilo = Hide And Seek
szpilki = High Heels
hippo = Hippopotamus
hokej = Hockey
porc = Hog, Pig
dom = House, Home
teme = Homework
med = Honey
hak = Hook
kun = Horse
赛马 = Horse Racing, Racehorse
zavodkoni = Horse Racing
ridning = Horse Riding, Ride
spital = Hospital
luftballon = Hot Air Balloon
kakao = Hot Chocolate
timgla = Hourglass
aro = Hula Hoop
nalkapeli = Hunger Games
lovec = Hunter
hekk = Hurdles
orkan = Hurricane
hypnose = Hypnotize
ishink = Ice Bucket
isslot = Ice Castle
ei = Ice Cream
isvaffel = Ice Cream Cone
isbil = Ice Cream Van
isbit = Ice Cube
patine = Ice Skates, Roller Blades
schaatsen = Ice Skates, Skating
rampouch = Ice Spike, Icicle
iglo = Igloo
insect = Insect, Bug
nastroj = Instrument
fer = Iron
bugelbrett = Ironing Board
jail = Jail, Prison
zele = Jelly
goma = Jellybeans
kwal = Jellyfish
sperky = Jewellery
puzzle = Puzzle, Jigsaw
behani = Jogging
ju = Juice
hopprep = Jump Rope
hopper = Jumping
selva = Jungle
klokan = Kangaroo
hok = Kennel
keczup = Ketchup, Tomato Ketchup
tetera = Kettle, Teapot
clavier = Keyboard
re = King
ku = Kiss
kote = Kitten
kiwi = Kiwi Fruit
kne = Knee
rytir = Knight
etiqueta = Label, Name Tag
labor = Laboratory
stige = Ladder
lago = Lake, Pond
lampione = Lamp Post, Streetlamp
klosz = Lampshade
lykta = Lantern
wasmand = Laundry Basket
lavahink = Lava Bucket
sekacka = Lawn Mower
corda = Lead, Rope, Tightrope
lov = Leaf, Leaves
lekkenddak = Leaking Roof
kuze = Leather
limonade = Lemonade, Soda
limonadikoju = Lemonade Stand
livvast = Lifejacket
ly = Light
interruptor = Light Switch, Switch
bec = Lightbulb
fyr = Lighthouse
lyn = Lightning
rayo = Lightning Strike
relampago = Lightning, Lightning Strike, Thunder
nufar = Lilypad
lev = Lion
usta = Lips, Mouth
ruj = Lipstick
odla = Lizard
lama = Llama
humr = Lobster
las = Lock
dyrk = Lock Pick
srub = Log Cabin
lolly = Lollipop
bagaz = Luggage
drwal = Lumberjack
kusuhli = Lump Of Coal
matbok = Lunchbox
kone = Machine
blad = Magazine
magico = Magic, Magician
taikamatto = Magic Carpet
joben = Magic Hat, Top Hat
toverstaf = Magic Wand
magmakub = Magma Cube
ima = Magnet
lupe = Magnifying Glass
posta = Post Office, Mail, Mailman
buzon = Mailbox
smink = Makeup
mamut = Mammoth
vila = Mansion, Village, Fairy
kulor = Marbles
fix = Marker
trh = Market
bezea = Marshmallow
lucifer = Matchstick
math = Math, Mathematics
madra/patja = Mattress
majone = Mayonnaise
mal = Measurement, Goal, Target
pulpet = Meatball
mecanic = Mechanic
medeltida hu = Medieval House
mote = Meeting
pepene = Melon, Watermelon
sirene = Mermaid
meteorit = Meteorite, Meteor

# Shortcut_List_Part4 (Mex-Rub)

mexic = Mexico
mikrofon = Microphone
mikroovn = Microwave
batido = Milkshake
melkweg = Milky Way
mjolkochkakor = Milk And Cookies
dul = Mine
lore = Minecart
spejl = Mirror
raket = Missile, Rocket, Rocket Ship
jmeli = Mistletoe
modern hui = Modern House
topo = Mole, Rat, Mouse
ecran = Monitor, Screen
mostri = Monsters
lua = Moon
los = Moose
rano = Morning
moto = Motorbike
berg = Mountain
muismat = Mousepad, Mouse Pad
ratoeira = Mousetrap
film = Movie
mor = Mummy, Mom
sval = Muscle
museo = Museum
pilz = Mushroom
musik = Music, Musical
keyboard = Musical Keyboard
musico = Musician
senf = Mustard
nacho = Nachos
stygglista = Naughty List
som = Nail
esmalte = Nail Polish
natur = Nature
colar = Necklace
ac = Needle
dolny = Nether
avi = Newspaper
yo = Night
incubo = Nightmare
nos = Nose
polonorte = North Pole
amme = Nurse
louskacek = Nutcracker
oa = Oasis
hav = Ocean
kraken = Octopus, Squid
birou = Office, Desk
ogr = Ogre
ol = Oil, Olympics(?)
omlet = Omelette
lokring = Onion Ring
orangensaft = Orange Juice
sad = Orchard, Sad
adorno = Ornament
strut = Ostrich
oter = Otter
ostra = Oyster
pakke = Package, Packet
klodka = Padlock
fargburk = Paint Bucket
verfpalet = Paint Palette
quadro = Painting, Picture, Frame, Paint
palac = Palace, Mansion
palma = Palm Tree
crepe = Pancake
papirfly = Paper Airplane
gem = Paperclip
padak = Parachute
loro = Parrot
fest = Party
festhat = Party Hat
pad = Pathway, Toad
dvur = Patio
vzor = Pattern
paw = Paws
pav = Peacock
mani = Peanut
pindakaa = Peanut Butter
penna = Pen, Pencil
etui = Pencil Case
femkant = Pentagon
parfem = Perfume
farao = Pharaoh
cover = Phone Case
ladegerat = Phone Charger
tavelram = Photoframe
foto = Photograph, Picture
fotograaf = Photograph, Photographer
pian = Piano
pico = Pickaxe
picle = Pickle
due = Pigeon
spagri = Piggy Bank
pude = Pillow
fronha = Pillowcase
pin = Pin, Pine Tree
pina = Pineapple
ananaspizza = Pineapple Pizza
pigna = Pinecone
乒乓球 = Ping Pong, Pong, Table Tennis
pingisbord = Ping Pong Table
pirat = Pirate
pirathat = Pirate Hat
piratskib = Pirate Ship
pist = Piston
alusta = Platform
hriste = Playground
nebbdyr = Platypus
fickur = Pocket Watch
podium = Podium, Stage
pogo = Pogo Stick
gift = Poison, Gift, Gifts
eisbar = Polar Bear
poli = Police, Police Officer
polizist = Policeman, Police Officer
polisbil = Police Car
esquadra = Police Station
basen = Pool, Swimming Pool
poolbord = Pool Table
pipoca = Popcorn
mak = Poppy
nanuk = Popsicle
postal = Postcard
afi = Poster
potd'or = Pot Of Gold
patata = Potato, Potatoes
esitelma = Presentation
brezel = Pretzel
prince = Prince, Princess
vezen = Prisoner
pociski = Projectile
propel = Propeller
pudim = Pudding
pla = Puddle
dyne = Pumpkin
rubikscube = Rubiks Cube, Puzzle Cube
pijama = Pyjamas, Onesie
quad = Quad Bike
kviksand = Quicksand
tobla = Quiver
raton = Racoon, Rat
circuito = Race Track, Track
travhast = Racehorse
vor = Raft
kolej = Railway
regen = Rain, Raindrop
rat = Rat, Steering Wheel
rokle = Ravine
ler = Reading
ren = Reindeer
mejer = Reaper
rudit = Redstone
ravintola = Restaurant
ri = Rice
rig = Rich
elv = River
strada = Road, Street
robo = Robot
rumskib = Rocket Ship, Spaceship
gungstol = Rocking Chair
achtbaan = Rollercoaster
ro = Rose
rosal = Rose Bush
rondo = Roundabout
elastik = Rubber Band
gummiand = Rubber Duck

# Shortcut_List_Part5 (Rud-Tu)

rudolf = Rudolph
correr = Runner, Running, Sprint
sa = Saddle
klui = Safe, Vault
velero = Sail, Sailboat, Sailing
mlok = Salamander
lax = Salmon
sul = Salt
saleepepe/sul a pepr = Salt And Pepper
sandslot = Sand Castle, Sandcastle
sandwich = Sandwich, Sandwiches
noel = Santa
jezisek = Santa Claus
sardine = Sardines
uydu = Satellite
so = Sauce
korv = Sausage
saxofon = Saxophone
leseni = Scaffold
vaha = Scale
strasak = Scarecrow
bang = Scared
skola = School
veda = Science
vedec = Scientist
skutr = Scooter
stir = Scorpion
tournevi = Screwdriver
le = Scythe
mage = Seagull
sjohast = Seahorse
sel = Seal
loc = Seat
tang = Seaweed
fro = Seed
omakuva = Self Portrait
symaskin = Sewing Machine
kanal = Sewer, Canal
sampon = Shampoo
shape = Shapes
haj = Shark
holeni = Shaving
ark = Sheet
plank = Shelf, Plank
ly = Shelter
stit = Shield
wrak = Shipwreck
沉船 = Shipwreck, Sunken Ship
tricou = T-Shirt, Shirt
lacet = Shoe Laces
handla = Shopping
loja = Shop, Store
handlepose = Shopping Bag
caddie = Shopping Trolley
umar = Shoulder
du = Shower
sinal = Signal
pia = Sink
skate = Skateboarding
skelet = Skeleton
ski = Ski, Skiing
rok = Skirt
kopf = Skull, Head
Skyskrapa = Skyscraper
uni = Sleep
spiwor = Sleeping Bag
slee = Sleigh
tobogan = Slide, Waterslide, Water Slide
sutsko = Slippers
slim = Slime
melc = Slug, Snail
sorriso = Smile, Smiley
fum = Smoke
vune = Smell
frappe = Smoothie
orm = Snake, Worm
teni = Sneakers, Tennis
snieg = Snow, Snowing
lumisota = Snowball Fight
snebold = Snowball
snowboard = Snowboarding
snefnug = Snowflake
balwan = Snowman
snoklot = Snow Globe
meia = Socks, Stocking
solsystem = Solar System
vojak = Soldier
lat = Song
lyd = Sound
spagety = Spaghetti
kopi = Spear
boxe = Speakers
lancha = Speedboat
sfera = Sphere, Globe
spin = Spider
spon = Sponge
ske = Spoon
sport = Sports
var = Spring
neilo = Square
sadetin = Sprinkler
egern = Squirrel
staje = Stables
stade = Stadium
lava = Stage, Lava
trappa = Staircase, Stairs
selo = Stamp
zeester = Starfish
socha = Statue
yllaty = Suprise
escada = Step Stool, Step Ladder, Stairs
calcada = Stepping Stones
note = Sticky Note
raia = Stingray
stoper = Stopwatch
lager = Storage
orage = Storm, Thunderstorm
herd = Stove
pai = Straw
fresa = Strawberry
fio = String, Wire
fort = Strong
ubad = Submarine
cukr = Sugar
pak = Suit
kufr = Suitcase
ete = Summer
lezak = Sunbed
solro = Sunflower
sunglasse = Sunglasses
sunketfly = Sunken Airplane
solly = Sunlight
swit = Sunrise
mataffar = Supermarket
surf = Surfing
suo = Swamp
troja = Sweater, Shirt
inot = Swimming
mec = Sword
mecoun = Swordfish
tuntnt = TNT Cannon
dug = Table Cloth
tabua = Tablet
kro = Tavern
taxi = Taxi, Cab
te = Tea
ceainic = Teapot, Teacup
lzy = Tears
teknik = Technology
bamse = Teddy Bear
dent = Teeth, Tooth
telefon = Telephone, Phone
telefooncel = Telephone Booth
telescop = Telescope
tv = Television
chram = Temple
tenisak = Tennis Ball
tennisbaan = Tennis Court
sms = Texting
erntedank = Thanksgiving
end = The End
grinch = The Grinch
teatr = Theatre
pretpark = Theme Park
teplomer = Thermometer
tyv = Thief
trun = Throne
tri = Tic Tac Toe
lippu = Ticket
tygr = Tiger
line = Tightrope, Line
cas = Time
aikakone = Time Machine
anvelopa = Tyre Swing
servetel = Tissue, Napkin
tost = Toast
toster = Toaster
toe = Toes
vessa = Toilet
rajce = Tomato
tong = Tongue
tool = Tools
tandfe = Tooth Fairy
tannkrem = Toothpaste
zolw = Tortoise, Turtle
totem = Totem Pole
vez = Tower
tourdepise = Tower Of Pisa
vojacek = Toy Soldier
trator = Tractor
trafic = Traffic
file = Traffic Jam
ampel = Traffic Lights
prives = Trailer
gare = Train Station
rail = Train Tracks
tag = Trains
trampolin = Trampoline, Diving Board
kuljetu = Transport, Transportation
val = Trap, Wave, Whale
bieznia = Treadmill
skat = Treasure
schatkist = Treasure Chest
tre = Tree
ra = Tree Frog
trehytte = Treehouse, Log Cabin
kolmio = Triangle
dreirad = Tricycle
hose = Trousers
lkw = Truck
tromba = Trumpet
banera = Tub, Bath Tub
drakamp = Tug Of War
tunel = Tunnel
peru = Turkey
tarn = Turret
trex = T-Rex

# Shortcut_List_Part6 (U-Z)

destnik = Umbrella
untot = Undead
pod woda = Under The Sea, Underwater
inorog = Unicorn
einrad = Unicycle
oppned = Upside Down
imuri = Vacuum
valentyn = Valentine
upir = Vampire
va = Vase
orto = Vegetable Garden
legume = Vegetables
fordon = Vehicle
bybo = Villager
fiol = Violin
volcan = Volcano
volei = Volleyball
vafa = Waffle
wand = Wand, Wall
pung = Wallet, Purse
mroz = Walrus
kriger = Warrior
pralka = Washing Machine
eau = Water
gavettone = Water Balloon 
waterfle = Water Bottle
vandspand = Water Bucket
aquapark = Water Park
fos = Waterfall
vandski = Waterski
saa = Weather
haat = Wedding
alianca = Wedding Ring
haakakku = Wedding Cake
vzpirani = Weightlifting
tja = Well
varulv = Werewolf
ble = Wheat
keulia = Wheelie
wir = Whirlpool
apito = Whistle
wiatrak = Windmill
okno = Window
ali = Wings
zima = Winter
wensput = Wishing Well
heksehu = Witch House
velho = Wizard
vlk = Wolf
la = Wool
taller = Workshop
sloopkogel = Wrecking Ball
kaarepaperi = Wrapping Paper
klic = Wrench
paini = Wrestling
pismo = Writing
wester = Western
xylofon = Xylophone
late = Yacht
gultegelvag = Yellow Brick Road
laurt = Yoghurt
zip = Zipper
zombiapokalypsi = Zombie Apocalypse
`;

function parseShortcuts(rawShortcuts: string) {
  return Object.fromEntries(
    rawShortcuts
      .toLowerCase()
      .split("\n")
      .filter(
        (line) => line.trim() && !line.startsWith("#") && line.includes("="),
      )
      .map((line) => {
        const segments = line.split("=").map((s) => s.trim());
        if (segments.length !== 2) return [null, null];

        const [key, values] = segments;
        return [
          key,
          values
            .split(",")
            .map((v) => v.trim())
            .filter(Boolean),
        ];
      })
      .filter(([key, _]) => key !== null),
  );
}

export function saveLocalShortcut(shortcuts: string) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem("custom_shortcuts", shortcuts);
}

export function getRawLocalShortcuts(): string {
  if (typeof window === "undefined") return "";
  return window.localStorage.getItem("custom_shortcuts") || "";
}

function getLocalShortcuts() {
  const customShortcuts = getRawLocalShortcuts();
  if (!customShortcuts) return {};

  return parseShortcuts(customShortcuts);
}

export const SHORTCUTS = parseShortcuts(RAW_SHORTCUTS);
export const SHORTCUTS_COUNT = Object.keys(SHORTCUTS).length;

export function getShortcut(shortcut: string): string[] | undefined {
  shortcut = shortcut.toLowerCase().trim();
  const localShortcuts = getLocalShortcuts();

  if (localShortcuts[shortcut]) return localShortcuts[shortcut];
  return SHORTCUTS[shortcut];
}
